"""add user_uid as foreign key to book

Revision ID: 43c0946d9cf6
Revises: 8001a524be6b
Create Date: 2025-08-17 00:42:16.725782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43c0946d9cf6'
down_revision: Union[str, Sequence[str], None] = '8001a524be6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.UUID(), nullable=True))
    op.create_foreign_key("fk_books_user_uid_users", 'books', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    op.execute(
        "UPDATE books SET user_uid = 'd3c1bacc-d14e-4f72-ad0f-bf2662df2daa'"
    )

    #  enforce NOT NULL
    op.alter_column("books", "user_uid", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
